permalink: /blog/:year/:month/:day/:title

baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Site specific context
title: Julia Elman
description: Julia Elman is a Design Team Manager based in Durham, North Carolina. 